config/routes.rb
Spree::Core::Engine.routes.append do
  namespace :admin do
    resource :google_merchant_settings
    resources :product_ad_channels do
      resources :product_ads
    end
    resources :product_ads

    get '/products/:product_id/product_ads', :to => 'product_ads#index'
  end
end

app/controllers/spree/admin/google_merchant_settings_controller.rb
class Spree::Admin::GoogleMerchantSettingsController < Spree::Admin::BaseController
  helper 'spree/admin/google_merchant'
  
  def update
    params.each do |name, value|
      next unless Spree::GoogleMerchant::Config.has_preference? name
      Spree::GoogleMerchant::Config[name] = value
    end
    
    respond_to do |format|
      format.html {
        redirect_to admin_google_merchant_settings_path
      }
    end
  end

end

app/views/spree/admin/google_merchant_settings/edit.html.erb
<h1><%= t("google_merchant.export_settings") %></h1>

<%= form_tag(admin_google_merchant_settings_path, :method => :put) do |f| %>
  <% [:title, :public_domain, :description, :product_category, :ftp_username, :ftp_password, :amazon_sftp_username, :amazon_sftp_password, :ebay_ftp_username, :ebay_ftp_password, :bing_sftp_username, :bing_sftp_password].each do |setting| %>
    <p><%= setting_field(setting) %></p>
  <% end %>

  <p class="form-buttons">
    <%= button Spree.t('update') %>
    <%= Spree.t("or") %> <%= link_to Spree.t("cancel"), admin_google_merchant_settings_url %>
  </p>
<% end %>

<% content_for :head do %>
  <style>
    .edit_google_merchant_configuration input { width: 250px; }
  </style>
<% end %>

app/views/spree/admin/google_merchant_settings/show.html.erb
<h1><%= t("google_merchant.export_settings") %></h1>

<table>
  <% [:title, :public_domain, :description, :product_category, :ftp_username, :amazon_sftp_username, :ebay_ftp_username, :bing_sftp_username].each do |setting| %>
    <%= setting_presentation_row(setting) %>
  <% end %>
  <%= setting_presentation_row(:ftp_password, true) %>
  <%= setting_presentation_row(:amazon_sftp_password, true) %>
  <%= setting_presentation_row(:ebay_ftp_password, true) %>
  <%= setting_presentation_row(:bing_sftp_password, true) %>
</table>

<p>
  <%= link_to_with_icon 'edit', Spree.t("edit"), edit_admin_google_merchant_settings_path %>
</p>